# presets.py
# Presets for the DDP Hub C++ engine (ESP32).
# Each preset maps to one of the hub's implemented fx IDs.
# "category" groups presets into tabs in the app UI.

from typing import Any, Dict, List, Optional

PRESETS: List[Dict[str, Any]] = [

    # ── Ambient ───────────────────────────────────────────────────
    {
        "id": "solid_core",
        "name": "Solid",
        "engine": "solid",
        "category": "Ambient",
        "bri": 255,
        "color": [255, 200, 160],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 200, 160]],
        "is_premium": False,
        "pack_id": None,
        "description": "Solid color. Change with the color picker.",
    },
    {
        "id": "breathe_warm",
        "name": "Breathe — Warm",
        "engine": "breathe",
        "category": "Ambient",
        "bri": 255,
        "color": [255, 180, 90],
        "sx": 110, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 180, 90]],
        "is_premium": False,
        "pack_id": None,
        "description": "Soft breathing brightness (warm white). Great for ambience.",
    },
    {
        "id": "breathe_cold",
        "name": "Breathe — Cold",
        "engine": "breathe",
        "category": "Ambient",
        "bri": 255,
        "color": [170, 220, 255],
        "sx": 105, "ix": 150, "pal": 0,
        "palette_size": 1,
        "palette_default": [[170, 220, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Soft breathing brightness (cool blue). Calm and minimal.",
    },
    {
        "id": "fade_warm",
        "name": "Fade",
        "engine": "fade",
        "category": "Ambient",
        "bri": 255,
        "color": [255, 180, 90],
        "sx": 100, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 180, 90]],
        "is_premium": False,
        "pack_id": None,
        "description": "Smooth fade in/out. Pick your color.",
    },
    {
        "id": "candle",
        "name": "Candle",
        "engine": "candle",
        "category": "Ambient",
        "bri": 255,
        "color": [255, 140, 20],
        "sx": 100, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 140, 20]],
        "is_premium": False,
        "pack_id": None,
        "description": "Flickering candle flame simulation.",
    },
    {
        "id": "sunrise",
        "name": "Sunrise",
        "engine": "sunrise",
        "category": "Ambient",
        "bri": 255,
        "color": [255, 120, 30],
        "sx": 60, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 120, 30]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Gradual sunrise from deep red to warm white. Colors generated automatically.",
    },

    # ── Dynamic ───────────────────────────────────────────────────
    {
        "id": "blink_core",
        "name": "Blink",
        "engine": "blink",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 120, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Simple blink. Pick any color.",
    },
    {
        "id": "strobe_white",
        "name": "Strobe",
        "engine": "strobe",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 160, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Sharp strobe flash. Speed controls frequency.",
    },
    {
        "id": "strobe_rainbow",
        "name": "Strobe Rainbow",
        "engine": "strobe_rainbow",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 140, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Strobe with random rainbow colors each flash.",
    },
    {
        "id": "colorwipe_blue",
        "name": "Color Wipe — Blue",
        "engine": "colorwipe",
        "category": "Dynamic",
        "bri": 255,
        "color": [120, 200, 255],
        "sx": 155, "ix": 175, "pal": 0,
        "palette_size": 1,
        "palette_default": [[120, 200, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Smooth color wipe across the strip.",
    },
    {
        "id": "colorwipe_sunset",
        "name": "Color Wipe — Sunset",
        "engine": "colorwipe",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 120, 60],
        "sx": 150, "ix": 185, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 120, 60]],
        "is_premium": False,
        "pack_id": None,
        "description": "Warm sunset wipe. Customize with color picker.",
    },
    {
        "id": "wipe_rev",
        "name": "Wipe Reversed",
        "engine": "wipe_rev",
        "category": "Dynamic",
        "bri": 255,
        "color": [0, 180, 255],
        "sx": 150, "ix": 175, "pal": 0,
        "palette_size": 1,
        "palette_default": [[0, 180, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Color wipe in reverse direction.",
    },
    {
        "id": "wipe_random",
        "name": "Wipe Random",
        "engine": "wipe_random",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 140, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Color wipe with a new random color every cycle.",
    },
    {
        "id": "meteor_white",
        "name": "Meteor",
        "engine": "meteor",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 165, "ix": 200, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Bright meteor with fading trail.",
    },
    {
        "id": "meteor_pink",
        "name": "Meteor — Neon",
        "engine": "meteor",
        "category": "Dynamic",
        "bri": 255,
        "color": [255, 60, 190],
        "sx": 170, "ix": 210, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 60, 190]],
        "is_premium": False,
        "pack_id": None,
        "description": "Neon pink meteor. Punchy and vibrant.",
    },
    {
        "id": "meteor_smooth",
        "name": "Meteor Smooth",
        "engine": "meteor_smooth",
        "category": "Dynamic",
        "bri": 255,
        "color": [200, 255, 255],
        "sx": 160, "ix": 200, "pal": 0,
        "palette_size": 1,
        "palette_default": [[200, 255, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Meteor with smooth anti-aliased trail.",
    },
    {
        "id": "scanner_purple",
        "name": "Scanner",
        "engine": "scanner",
        "category": "Dynamic",
        "bri": 255,
        "color": [180, 80, 255],
        "sx": 130, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[180, 80, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Bouncing scanner dot with fading trail. Pick your color.",
    },
    {
        "id": "scanner_dual",
        "name": "Scanner Dual",
        "engine": "scanner_dual",
        "category": "Dynamic",
        "bri": 255,
        "color": [0, 220, 255],
        "sx": 130, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[0, 220, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Two scanner dots bouncing from both ends.",
    },
    {
        "id": "comet_ice",
        "name": "Comet",
        "engine": "comet",
        "category": "Dynamic",
        "bri": 255,
        "color": [180, 220, 255],
        "sx": 160, "ix": 200, "pal": 0,
        "palette_size": 1,
        "palette_default": [[180, 220, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Gaussian comet chase. Soft and smooth.",
    },
    {
        "id": "running_cyan",
        "name": "Running Lights",
        "engine": "running",
        "category": "Dynamic",
        "bri": 255,
        "color": [0, 200, 255],
        "sx": 140, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[0, 200, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Smooth sine wave running along the strip. Pick your color.",
    },

    # ── Rainbow ───────────────────────────────────────────────────
    {
        "id": "rainbow_core",
        "name": "Rainbow",
        "engine": "rainbow",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Classic rainbow cycle. Colors generated automatically.",
    },
    {
        "id": "colorloop",
        "name": "Color Loop",
        "engine": "colorloop",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 100, 200],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 100, 200]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "All LEDs slowly cycle through rainbow hues.",
    },
    {
        "id": "chase_rainbow",
        "name": "Chase Rainbow",
        "engine": "chase_rainbow",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 130, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "A dot chases the strip, cycling through rainbow colors.",
    },
    {
        "id": "gradient",
        "name": "Gradient",
        "engine": "gradient",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 100, 0],
        "sx": 100, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 100, 0]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Smooth moving gradient across the strip.",
    },
    {
        "id": "colorwaves",
        "name": "Colorwaves",
        "engine": "colorwaves",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Beautiful flowing color waves from palette.",
    },
    {
        "id": "bpm",
        "name": "BPM",
        "engine": "bpm",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Beat-synced palette animation. Speed controls BPM.",
    },
    {
        "id": "fill_noise",
        "name": "Fill Noise",
        "engine": "fill_noise",
        "category": "Rainbow",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Perlin noise-based color fill from palette.",
    },

    # ── Nature ────────────────────────────────────────────────────
    {
        "id": "fire_main",
        "name": "Fire",
        "engine": "fire_sync",
        "category": "Nature",
        "bri": 255,
        "color": [255, 140, 30],
        "sx": 210, "ix": 60, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 140, 30]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Realistic Fire2012 algorithm. Colors generated automatically.",
    },
    {
        "id": "fire_flicker",
        "name": "Fire Flicker",
        "engine": "fire_flicker",
        "category": "Nature",
        "bri": 255,
        "color": [255, 100, 10],
        "sx": 150, "ix": 100, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 100, 10]],
        "is_premium": False,
        "pack_id": None,
        "description": "Random fire-like flicker. Pick your flame color.",
    },
    {
        "id": "pacifica",
        "name": "Pacifica",
        "engine": "pacifica",
        "category": "Nature",
        "bri": 255,
        "color": [0, 120, 200],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[0, 120, 200]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Ocean wave simulation with deep blue-green hues.",
    },
    {
        "id": "rain",
        "name": "Rain",
        "engine": "rain",
        "category": "Nature",
        "bri": 255,
        "color": [0, 160, 255],
        "sx": 130, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[0, 160, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Raindrops falling down the strip. Pick your color.",
    },

    # ── Twinkle ───────────────────────────────────────────────────
    {
        "id": "twinkle_stars",
        "name": "Twinkle — Stars",
        "engine": "twinkle",
        "category": "Twinkle",
        "bri": 255,
        "color": [170, 210, 255],
        "sx": 135, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[170, 210, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Random star-like twinkles. Pick your color.",
    },
    {
        "id": "twinkle_gold",
        "name": "Twinkle — Gold",
        "engine": "twinkle",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 200, 110],
        "sx": 140, "ix": 175, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 200, 110]],
        "is_premium": False,
        "pack_id": None,
        "description": "Warm golden sparkles. Great on diffusers.",
    },
    {
        "id": "twinkle_random",
        "name": "Twinkle Random",
        "engine": "twinkle_random",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 140, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Twinkle with random rainbow colors.",
    },
    {
        "id": "twinkle_fade",
        "name": "Twinkle Fade",
        "engine": "twinkle_fade",
        "category": "Twinkle",
        "bri": 255,
        "color": [180, 180, 255],
        "sx": 130, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[180, 180, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Twinkles that smoothly fade out. Pick your color.",
    },
    {
        "id": "twinklefox",
        "name": "Twinklefox",
        "engine": "twinklefox",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 100, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Gentle per-pixel twinkle with random timings from palette.",
    },
    {
        "id": "twinklefox_party",
        "name": "Twinklefox Party",
        "engine": "twinklefox_party",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 130, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Twinklefox with vivid party-palette colors.",
    },
    {
        "id": "sparkle",
        "name": "Sparkle",
        "engine": "sparkle",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 220, 180],
        "sx": 150, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 220, 180]],
        "is_premium": False,
        "pack_id": None,
        "description": "Base color with random bright white flashes. Pick your color.",
    },
    {
        "id": "sparkle_dark",
        "name": "Sparkle Dark",
        "engine": "sparkle_dark",
        "category": "Twinkle",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 150, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Random dark flashes on lit background. Pick your color.",
    },

    # ── Party ─────────────────────────────────────────────────────
    {
        "id": "juggle",
        "name": "Juggle",
        "engine": "juggle",
        "category": "Party",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Multiple colored dots juggling back and forth.",
    },
    {
        "id": "starburst",
        "name": "Starburst",
        "engine": "starburst",
        "category": "Party",
        "bri": 255,
        "color": [255, 200, 100],
        "sx": 128, "ix": 180, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 200, 100]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Sparks burst outward from random points.",
    },
    {
        "id": "fireworks_multi",
        "name": "Fireworks",
        "engine": "fireworks",
        "category": "Party",
        "bri": 255,
        "color": [255, 200, 100],
        "sx": 90, "ix": 190, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 200, 100]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Colorful firework explosions. Colors generated automatically.",
    },
    {
        "id": "fireworks1d",
        "name": "Fireworks 1D",
        "engine": "fireworks1d",
        "category": "Party",
        "bri": 255,
        "color": [255, 200, 100],
        "sx": 60, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 200, 100]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Physics-based 1D fireworks: rockets fly up and explode with gravity.",
    },
    {
        "id": "bouncing_balls",
        "name": "Bouncing Balls",
        "engine": "bouncing_balls",
        "category": "Party",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 140, "ix": 160, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Rainbow balls bounce with gravity. Intensity controls ball count.",
    },
    {
        "id": "colorful",
        "name": "Colorful",
        "engine": "colorful",
        "category": "Party",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 128, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Each LED a different saturated hue, shifting over time.",
    },
    {
        "id": "dissolve",
        "name": "Dissolve",
        "engine": "dissolve",
        "category": "Party",
        "bri": 255,
        "color": [200, 200, 255],
        "sx": 120, "ix": 200, "pal": 0,
        "palette_size": 1,
        "palette_default": [[200, 200, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Pixels appear and dissolve randomly. Intensity controls density.",
    },
    {
        "id": "ripple",
        "name": "Ripple",
        "engine": "ripple",
        "category": "Party",
        "bri": 255,
        "color": [100, 180, 255],
        "sx": 120, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[100, 180, 255]],
        "is_premium": False,
        "pack_id": None,
        "description": "Expanding wave from a random point. Pick your color.",
    },

    # ── Special ───────────────────────────────────────────────────
    {
        "id": "lightning",
        "name": "Lightning",
        "engine": "lightning",
        "category": "Special",
        "bri": 255,
        "color": [255, 255, 255],
        "sx": 100, "ix": 180, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 255, 255]],
        "color_locked": True,
        "is_premium": False,
        "pack_id": None,
        "description": "Dramatic random lightning bolts. Speed controls frequency.",
    },
    {
        "id": "halloween_eyes",
        "name": "Halloween Eyes",
        "engine": "halloween_eyes",
        "category": "Special",
        "bri": 255,
        "color": [255, 0, 0],
        "sx": 80, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 0, 0]],
        "is_premium": False,
        "pack_id": None,
        "description": "Pair of glowing eyes appear and stare. Pick eye color.",
    },
    {
        "id": "heartbeat",
        "name": "Heartbeat",
        "engine": "heartbeat",
        "category": "Special",
        "bri": 255,
        "color": [255, 0, 60],
        "sx": 100, "ix": 128, "pal": 0,
        "palette_size": 1,
        "palette_default": [[255, 0, 60]],
        "is_premium": False,
        "pack_id": None,
        "description": "Double-pulse heartbeat rhythm. Pick your color.",
    },
]


def find_preset(preset_id: str) -> Optional[Dict[str, Any]]:
    pid = (preset_id or "").strip()
    for p in PRESETS:
        if p.get("id") == pid:
            return p
    return None
